# GeniusEngine Makefile
# All build artifacts go to build/

# Auto-parallelise: use all available CPU cores
MAKEFLAGS += -j$(shell nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 4)

# Include platform config (generated by configure.sh)
-include build.config

# Defaults if no build.config
CXX ?= clang++
CXXFLAGS ?= -std=c++20 -Wall -Wextra -O2 -fPIC
SHARED_EXT ?= .dylib
SHARED_FLAG ?= -dynamiclib
PLATFORM ?= macos
HAS_VULKAN ?= 0

# OpenMP (via Homebrew libomp on macOS)
ifeq ($(PLATFORM),macos)
OMP_CFLAGS = -Xpreprocessor -fopenmp -I/opt/homebrew/opt/libomp/include
OMP_LIBS = -L/opt/homebrew/opt/libomp/lib -lomp
else
OMP_CFLAGS = -fopenmp
OMP_LIBS = -fopenmp
endif
CXXFLAGS += $(OMP_CFLAGS)

# Vulkan defines
ifeq ($(HAS_VULKAN),1)
CXXFLAGS += -DGE_HAS_VULKAN $(VULKAN_CFLAGS)
endif

# Directories
SRC_DIR = src
BUILD_DIR = build
OBJ_DIR = $(BUILD_DIR)/obj
LIB_DIR = $(BUILD_DIR)/lib
BIN_DIR = $(BUILD_DIR)/bin

# ImGui source (bundled in third_party)
IMGUI_DIR = third_party/imgui
IMGUI_SRCS = $(IMGUI_DIR)/imgui.cpp $(IMGUI_DIR)/imgui_draw.cpp \
             $(IMGUI_DIR)/imgui_tables.cpp $(IMGUI_DIR)/imgui_widgets.cpp \
             $(IMGUI_DIR)/backends/imgui_impl_glfw.cpp \
             $(IMGUI_DIR)/backends/imgui_impl_opengl3.cpp
ifeq ($(PLATFORM),macos)
IMGUI_METAL_SRC = $(IMGUI_DIR)/backends/imgui_impl_metal.mm
IMGUI_METAL_OBJ = $(OBJ_DIR)/imgui/backends/imgui_impl_metal.o
endif

# ImGui Vulkan backend
ifeq ($(HAS_VULKAN),1)
IMGUI_VULKAN_SRC = $(IMGUI_DIR)/backends/imgui_impl_vulkan.cpp
IMGUI_VULKAN_OBJ = $(OBJ_DIR)/imgui/backends/imgui_impl_vulkan.o
endif

# GLAD source (bundled, glad2 generates gl.c)
GLAD_SRC = third_party/glad/src/gl.c

# Include paths
INCLUDES = -I$(SRC_DIR) -Ithird_party/glad/include -Ithird_party/stb -I$(IMGUI_DIR) -I$(IMGUI_DIR)/backends \
           $(GLFW_CFLAGS) $(GLM_CFLAGS)

# Shaderc (for Vulkan SPIR-V compilation)
ifeq ($(HAS_VULKAN),1)
SHADERC_LIBS = -L/usr/local/lib -lshaderc_shared
INCLUDES += -I/usr/local/include
endif

# Libraries
LIBS = $(GLFW_LIBS) $(FRAMEWORKS) -ldl

# --- Source files per library ---

# GAPI (OpenGL backend)
GAPI_SRCS = $(SRC_DIR)/graphics/opengl/GLContext.cpp \
            $(SRC_DIR)/graphics/opengl/GLShader.cpp \
            $(SRC_DIR)/graphics/opengl/GLBuffer.cpp \
            $(SRC_DIR)/graphics/opengl/GLTexture.cpp
GAPI_OBJS = $(patsubst $(SRC_DIR)/%.cpp,$(OBJ_DIR)/%.o,$(GAPI_SRCS))

# Factory (plain C++, conditionally includes Metal/Vulkan headers)
FACTORY_SRC = $(SRC_DIR)/graphics/Factory.cpp
FACTORY_OBJ = $(OBJ_DIR)/graphics/Factory.o

# Metal backend (macOS only)
ifeq ($(PLATFORM),macos)
METAL_SRCS = $(SRC_DIR)/graphics/metal/MetalContext.mm \
             $(SRC_DIR)/graphics/metal/MetalShader.mm \
             $(SRC_DIR)/graphics/metal/MetalBuffer.mm \
             $(SRC_DIR)/graphics/metal/MetalTexture.mm
METAL_OBJS = $(patsubst $(SRC_DIR)/%.mm,$(OBJ_DIR)/%.o,$(METAL_SRCS))
METAL_FRAMEWORKS = -framework Metal -framework QuartzCore -framework MetalKit
LIB_GAPI_METAL = $(LIB_DIR)/libgapi_metal$(SHARED_EXT)
endif

# Vulkan backend (optional)
ifeq ($(HAS_VULKAN),1)
VULKAN_SRCS = $(SRC_DIR)/graphics/vulkan/VulkanContext.cpp \
              $(SRC_DIR)/graphics/vulkan/VulkanBuffer.cpp \
              $(SRC_DIR)/graphics/vulkan/VulkanShader.cpp \
              $(SRC_DIR)/graphics/vulkan/VulkanTexture.cpp
VULKAN_OBJS = $(patsubst $(SRC_DIR)/%.cpp,$(OBJ_DIR)/%.o,$(VULKAN_SRCS))
LIB_GAPI_VULKAN = $(LIB_DIR)/libgapi_vulkan$(SHARED_EXT)
endif

# Engine
ENGINE_SRCS = $(SRC_DIR)/engine/Window.cpp \
              $(SRC_DIR)/engine/Camera.cpp \
              $(SRC_DIR)/engine/Input.cpp \
              $(SRC_DIR)/engine/Mesh.cpp \
              $(SRC_DIR)/engine/Material.cpp \
              $(SRC_DIR)/engine/Renderer.cpp \
              $(SRC_DIR)/engine/AssetLoader.cpp \
              $(SRC_DIR)/engine/Scene.cpp \
              $(SRC_DIR)/engine/Engine.cpp
ENGINE_OBJS = $(patsubst $(SRC_DIR)/%.cpp,$(OBJ_DIR)/%.o,$(ENGINE_SRCS))

# UI
UI_SRC_MM = $(SRC_DIR)/ui/UI.mm
UI_OBJ = $(OBJ_DIR)/ui/UI.o
PANEL_SRC = $(SRC_DIR)/ui/Panel.cpp
PANEL_OBJ = $(OBJ_DIR)/ui/Panel.o

# ImGui objects
IMGUI_OBJS = $(patsubst $(IMGUI_DIR)/%.cpp,$(OBJ_DIR)/imgui/%.o,$(IMGUI_SRCS))

# GLAD object
GLAD_OBJ = $(OBJ_DIR)/glad.o

# App
APP_SRC = $(SRC_DIR)/app/SolarSystemApp.cpp
APP_OBJ = $(OBJ_DIR)/app/SolarSystemApp.o

# Targets
TARGET = $(BIN_DIR)/GeniusEngine
LIB_GAPI = $(LIB_DIR)/libgapi_opengl$(SHARED_EXT)
LIB_ENGINE = $(LIB_DIR)/libengine$(SHARED_EXT)
LIB_UI = $(LIB_DIR)/libui$(SHARED_EXT)

.PHONY: all clean dirs

all: dirs $(TARGET)

dirs:
	@mkdir -p $(OBJ_DIR)/graphics/opengl $(OBJ_DIR)/graphics/metal $(OBJ_DIR)/graphics/vulkan $(OBJ_DIR)/graphics
	@mkdir -p $(OBJ_DIR)/engine $(OBJ_DIR)/ui $(OBJ_DIR)/app
	@mkdir -p $(OBJ_DIR)/imgui/backends
	@mkdir -p $(LIB_DIR) $(BIN_DIR)

# --- Compile rules ---

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp
	$(CXX) $(CXXFLAGS) $(INCLUDES) -c $< -o $@

# Objective-C++ for Metal backend
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.mm
	$(CXX) $(CXXFLAGS) $(INCLUDES) -fobjc-arc -c $< -o $@

$(OBJ_DIR)/imgui/%.o: $(IMGUI_DIR)/%.cpp
	$(CXX) $(CXXFLAGS) $(INCLUDES) -c $< -o $@

$(OBJ_DIR)/imgui/%.o: $(IMGUI_DIR)/%.mm
	$(CXX) $(CXXFLAGS) $(INCLUDES) -fobjc-arc -c $< -o $@

$(GLAD_OBJ): $(GLAD_SRC)
	$(CXX) $(CXXFLAGS) $(INCLUDES) -c $< -o $@

# --- Shared libraries ---

$(LIB_GAPI): $(GAPI_OBJS) $(GLAD_OBJ)
	$(CXX) $(SHARED_FLAG) -o $@ $^ $(LIBS)

# Metal backend (macOS only)
ifeq ($(PLATFORM),macos)
$(LIB_GAPI_METAL): $(METAL_OBJS) $(LIB_GAPI)
	$(CXX) $(SHARED_FLAG) -o $@ $(METAL_OBJS) -L$(LIB_DIR) -lgapi_opengl $(GLFW_LIBS) $(FRAMEWORKS) $(METAL_FRAMEWORKS) -ldl
endif

# Vulkan backend (optional)
ifeq ($(HAS_VULKAN),1)
$(LIB_GAPI_VULKAN): $(VULKAN_OBJS) $(LIB_GAPI)
	$(CXX) $(SHARED_FLAG) -o $@ $(VULKAN_OBJS) -L$(LIB_DIR) -lgapi_opengl $(GLFW_LIBS) $(VULKAN_LIBS) $(SHADERC_LIBS) $(FRAMEWORKS) -ldl
endif

# Compute engine dependencies and link flags
ENGINE_LINK_LIBS = -L$(LIB_DIR) -lgapi_opengl
ENGINE_DEPS = $(LIB_GAPI)

ifeq ($(PLATFORM),macos)
ENGINE_LINK_LIBS += -lgapi_metal $(METAL_FRAMEWORKS)
ENGINE_DEPS += $(LIB_GAPI_METAL)
endif

ifeq ($(HAS_VULKAN),1)
ENGINE_LINK_LIBS += -lgapi_vulkan $(VULKAN_LIBS) $(SHADERC_LIBS)
ENGINE_DEPS += $(LIB_GAPI_VULKAN)
endif

$(LIB_ENGINE): $(ENGINE_OBJS) $(FACTORY_OBJ) $(ENGINE_DEPS)
	$(CXX) $(SHARED_FLAG) -o $@ $(ENGINE_OBJS) $(FACTORY_OBJ) $(ENGINE_LINK_LIBS) $(LIBS)

# UI library
UI_LINK_LIBS = -L$(LIB_DIR) -lgapi_opengl
UI_DEPS = $(LIB_GAPI)

ifeq ($(PLATFORM),macos)
UI_LINK_LIBS += -lgapi_metal $(METAL_FRAMEWORKS)
UI_DEPS += $(LIB_GAPI_METAL)
endif

ifeq ($(HAS_VULKAN),1)
UI_LINK_LIBS += -lgapi_vulkan $(VULKAN_LIBS)
UI_DEPS += $(LIB_GAPI_VULKAN)
endif

$(LIB_UI): $(UI_OBJ) $(PANEL_OBJ) $(IMGUI_OBJS) $(IMGUI_METAL_OBJ) $(IMGUI_VULKAN_OBJ) $(UI_DEPS)
	$(CXX) $(SHARED_FLAG) -o $@ $(UI_OBJ) $(PANEL_OBJ) $(IMGUI_OBJS) $(IMGUI_METAL_OBJ) $(IMGUI_VULKAN_OBJ) $(UI_LINK_LIBS) $(LIBS)

# --- Final binary ---

APP_LINK_LIBS = -L$(LIB_DIR) -lgapi_opengl -lengine -lui
APP_LINK_DEPS = $(ENGINE_DEPS) $(LIB_ENGINE) $(LIB_UI)

ifeq ($(PLATFORM),macos)
APP_LINK_LIBS += -lgapi_metal $(METAL_FRAMEWORKS)
RPATH_FLAG = -Wl,-rpath,@loader_path/../lib
ifneq ($(VULKAN_LIB_DIR),)
RPATH_FLAG += -Wl,-rpath,$(VULKAN_LIB_DIR)
endif
endif

ifeq ($(HAS_VULKAN),1)
APP_LINK_LIBS += -lgapi_vulkan $(VULKAN_LIBS) $(SHADERC_LIBS)
endif

ifeq ($(PLATFORM),linux)
RPATH_FLAG = -Wl,-rpath,'$$ORIGIN/../lib'
endif

$(TARGET): $(APP_OBJ) $(APP_LINK_DEPS)
	$(CXX) $(CXXFLAGS) -o $@ $(APP_OBJ) $(APP_LINK_LIBS) $(LIBS) $(OMP_LIBS) $(RPATH_FLAG)

# --- Clean ---

clean:
	rm -rf $(BUILD_DIR)
